// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAkMqm8y3A7RfF2NZioRiieHLVQqCyxGc',
    appId: '1:1051878920808:web:cc88ea59294132517ea1dd',
    messagingSenderId: '1051878920808',
    projectId: 'weather-login-cefd3',
    authDomain: 'weather-login-cefd3.firebaseapp.com',
    storageBucket: 'weather-login-cefd3.firebasestorage.app',
    measurementId: 'G-83X275Y7KN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwFJQl87lTLbbVnpe2Bnr5QuLJlWRPQ_w',
    appId: '1:1051878920808:android:005885afe8316b267ea1dd',
    messagingSenderId: '1051878920808',
    projectId: 'weather-login-cefd3',
    storageBucket: 'weather-login-cefd3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzpQtd0xA_JFTCGsqKLwXMsi5ygqZE4pE',
    appId: '1:1051878920808:ios:d507d4e34d1a1cc37ea1dd',
    messagingSenderId: '1051878920808',
    projectId: 'weather-login-cefd3',
    storageBucket: 'weather-login-cefd3.firebasestorage.app',
    iosBundleId: 'com.example.weatherAppWithLogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzpQtd0xA_JFTCGsqKLwXMsi5ygqZE4pE',
    appId: '1:1051878920808:ios:d507d4e34d1a1cc37ea1dd',
    messagingSenderId: '1051878920808',
    projectId: 'weather-login-cefd3',
    storageBucket: 'weather-login-cefd3.firebasestorage.app',
    iosBundleId: 'com.example.weatherAppWithLogin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAkMqm8y3A7RfF2NZioRiieHLVQqCyxGc',
    appId: '1:1051878920808:web:be19a878370fbd6b7ea1dd',
    messagingSenderId: '1051878920808',
    projectId: 'weather-login-cefd3',
    authDomain: 'weather-login-cefd3.firebaseapp.com',
    storageBucket: 'weather-login-cefd3.firebasestorage.app',
    measurementId: 'G-8058VE86QZ',
  );
}
